package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import Logic.*;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

public class AddPolyStaff extends javax.swing.JFrame {

    /**
     * Creates new form AddM
     */
    public AddPolyStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        jLabel24 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        f = new javax.swing.JRadioButton();
        m = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        textposition = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jDay = new javax.swing.JComboBox<>();
        Jmonth = new javax.swing.JComboBox<>();
        Jyear = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        lbl = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        pnTitle = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(241, 247, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 600));

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(21, 50, 112));
        jLabel23.setText("Add Staff Member");

        panel3.setBackground(new java.awt.Color(205, 228, 242));
        panel3.setPreferredSize(new java.awt.Dimension(900, 400));

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(21, 50, 112));
        jLabel24.setText("First Name:");

        txtname.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtname.setForeground(new java.awt.Color(21, 50, 112));

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(21, 50, 112));
        jLabel25.setText("Surname:");

        txtlname.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtlname.setForeground(new java.awt.Color(21, 50, 112));

        jLabel26.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(21, 50, 112));
        jLabel26.setText("Gender:");

        buttonGroup1.add(f);
        f.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        f.setForeground(new java.awt.Color(21, 50, 112));
        f.setText("Female");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        buttonGroup1.add(m);
        m.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        m.setForeground(new java.awt.Color(21, 50, 112));
        m.setText("Male");

        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(21, 50, 112));
        jLabel27.setText("Position");

        textposition.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        textposition.setForeground(new java.awt.Color(21, 50, 112));

        jLabel29.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(21, 50, 112));
        jLabel29.setText("Date of Birth:");

        jDay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jDay.setForeground(new java.awt.Color(21, 50, 112));
        jDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Jmonth.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        Jmonth.setForeground(new java.awt.Color(21, 50, 112));
        Jmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May ", "June", "July", "August", "September", "October", "November", "December" }));
        Jmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmonthActionPerformed(evt);
            }
        });

        Jyear.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        Jyear.setForeground(new java.awt.Color(21, 50, 112));
        Jyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008" }));

        jLabel30.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(21, 50, 112));
        jLabel30.setText("Phone number:");

        txtPhone.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(21, 50, 112));

        jButton13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jButton13.setForeground(new java.awt.Color(21, 50, 112));
        jButton13.setText("Register");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        txtAddress.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(21, 50, 112));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        lbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        lbl.setForeground(new java.awt.Color(21, 50, 112));
        lbl.setText("Address:");

        txtDepartment.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDepartment.setForeground(new java.awt.Color(21, 50, 112));

        jLabel28.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(21, 50, 112));
        jLabel28.setText("Department:");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(txtname)
                    .addComponent(txtlname)
                    .addComponent(textposition, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(f)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl)
                    .addComponent(jLabel28)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDepartment, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addGap(392, 392, 392))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f)
                            .addComponent(m))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(jButton13)
                .addContainerGap())
        );

        pnTitle.setBackground(new java.awt.Color(205, 228, 242));
        pnTitle.setPreferredSize(new java.awt.Dimension(950, 110));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/BackBtn.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(21, 50, 112));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/polytechnic Gym System.png"))); // NOI18N
        jLabel22.setPreferredSize(new java.awt.Dimension(1353, 135));

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addContainerGap())
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTitleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTitleLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton15)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jLabel23)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(pnTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       String firstName = txtname.getText();
String surname = txtlname.getText();
String gender = "";
try {
    if (f.isSelected()) {
        gender = "Female";
    } else if (m.isSelected()) {
        gender = "Male";
    } else {
        // Gender not selected
        JOptionPane.showMessageDialog(null, "Please select a gender.", "Missing Input", JOptionPane.ERROR_MESSAGE);
        return; // Stop further execution if an exception occurs
    }
} catch (NullPointerException e) {
    // Handle the exception when the radio buttons are not initialized properly
    JOptionPane.showMessageDialog(null, "Please select a gender.", "Missing Input", JOptionPane.ERROR_MESSAGE);
    return; // Stop further execution if an exception occurs
}

String position;
try {
    position = textposition.getText();
    if (position.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter a position.", "Missing Input", JOptionPane.ERROR_MESSAGE);
        return; // Stop further execution if an exception occurs
    }

    if (position.length() < 3) {
        JOptionPane.showMessageDialog(null, "Please enter a position with at least three letters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        return; // Stop further execution if an exception occurs
    }
} catch (NullPointerException e) {
    // Handle the exception when `textposition` is null
    JOptionPane.showMessageDialog(null, "Please enter a position.", "Missing Input", JOptionPane.ERROR_MESSAGE);
    return; // Stop further execution if an exception occurs
}

String department;
try {
    department = txtDepartment.getText();
    if (department.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select a department.", "Missing Input", JOptionPane.ERROR_MESSAGE);
        return; // Stop further execution if an exception occurs
    }
} catch (NullPointerException e) {
    // Handle the exception when `txtDepartment` is null
    JOptionPane.showMessageDialog(null, "Please select a department.", "Missing Input", JOptionPane.ERROR_MESSAGE);
    return; // Stop further execution if an exception occurs
}

String address;
try {
    address = txtAddress.getText();
    if (address.length() < 4) {
        JOptionPane.showMessageDialog(null, "Please enter an address with at least four letters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        return; // Stop further execution if an exception occurs
    }
} catch (NullPointerException e) {
    // Handle the exception when `txtAddress` is null
    JOptionPane.showMessageDialog(null, "Please enter an address.", "Missing Input", JOptionPane.ERROR_MESSAGE);
    return; // Stop further execution if an exception occurs
}

String day = (String) jDay.getSelectedItem();
String month = (String) Jmonth.getSelectedItem();
String year = (String) Jyear.getSelectedItem();
if (day == "Day" || month == "Month" || year == "Year" || day.isEmpty() || month.isEmpty() || year.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please selecta valid date of birth.", "Missing Input", JOptionPane.ERROR_MESSAGE);
    return; // Stop further execution if an exception occurs
}
String dateOfBirth = day + month + year;

int phone;
try {
    phone = Integer.parseInt(txtPhone.getText());
} catch (NumberFormatException e) {
    // Handle the exception when the phone number cannot be parsed as an integer
    JOptionPane.showMessageDialog(null, "Please enter a valid phone number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
    return; // Stop further execution if an exception occurs
}

boolean hasPt = false;

// Validate first name and surname
if (firstName.length() < 2) {
    JOptionPane.showMessageDialog(null, "Please enter a first name with at least two letters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
    return; // Stop further execution if an exception occurs
}

if (surname.length() < 2) {
    JOptionPane.showMessageDialog(null, "Please enter a surname with at least two letters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
    return; // Stop further execution if an exception occurs
}

txtname.setText("");
txtlname.setText("");
txtAddress.setText("");
txtPhone.setText("");
textposition.setText("");
txtDepartment.setText("");
jDay.setSelectedIndex(0);
Jmonth.setSelectedIndex(0);
Jyear.setSelectedIndex(0);
buttonGroup1.clearSelection();

JOptionPane.showMessageDialog(null, "Registered successfully", "Done", JOptionPane.PLAIN_MESSAGE);
Employee personalTrainer = null;

// Create a newStaff object and add it to the memberList
Staff newStaff = new Staff(position, department, firstName, surname, dateOfBirth, phone, gender, hasPt, address, personalTrainer);

try {
    GymSystem.memberList.add(newStaff);
} catch (NullPointerException e) {
    // Handle the exception when `GymSystem.memberList` is null
    JOptionPane.showMessageDialog(null, "An error occurred while processing your request. Please try again later.", "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
    return; // Stop further execution if an exception occurs
}

for (Member staff : GymSystem.memberList) {
    System.out.println(staff.toString());
}
System.out.println("Done !");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void JmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JmonthActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddMem().setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPolyStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPolyStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPolyStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPolyStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPolyStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jmonth;
    private javax.swing.JComboBox<String> Jyear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton f;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JComboBox<String> jDay;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JRadioButton m;
    private java.awt.Panel panel3;
    private javax.swing.JPanel pnTitle;
    private javax.swing.JTextField textposition;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
