package GUI;

import GUI.AddMem;
import java.awt.Dimension;
import java.awt.Toolkit;
import Logic.*;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

public class AddStudent extends javax.swing.JFrame {

    private static int nextID = 1000;

    /**
     * Creates new form AddM
     */
    public AddStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panel3 = new java.awt.Panel();
        jLabel24 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtLast = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        RBF = new javax.swing.JRadioButton();
        RBM = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        txtCourse = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        JDay = new javax.swing.JComboBox<>();
        Jmonth = new javax.swing.JComboBox<>();
        Jyear = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        txtTeam = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        pnTitle = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(241, 247, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 600));

        panel3.setBackground(new java.awt.Color(205, 228, 242));
        panel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        panel3.setName(""); // NOI18N
        panel3.setPreferredSize(new java.awt.Dimension(900, 400));

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(21, 50, 112));
        jLabel24.setText("First Name:");

        txtName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(21, 50, 112));
        jLabel25.setText("Surname:");

        txtLast.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(21, 50, 112));
        jLabel26.setText("Gender:");

        group1.add(RBF);
        RBF.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        RBF.setForeground(new java.awt.Color(21, 50, 112));
        RBF.setText("Female");
        RBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBFActionPerformed(evt);
            }
        });

        group1.add(RBM);
        RBM.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        RBM.setForeground(new java.awt.Color(21, 50, 112));
        RBM.setText("Male");
        RBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(21, 50, 112));
        jLabel27.setText("Course Name:");

        txtCourse.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(21, 50, 112));
        jLabel29.setText("Date of Birth:");

        JDay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        JDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Jmonth.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        Jmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May ", "June", "July", "August", "September", "October", "November", "December" }));
        Jmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmonthActionPerformed(evt);
            }
        });

        Jyear.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        Jyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006" }));
        Jyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JyearActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(21, 50, 112));
        jLabel30.setText("Phone number:");

        txtphone.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(21, 50, 112));
        jLabel33.setText("Sport Team:");

        jButton13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jButton13.setText("Register");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        txtAddress.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(21, 50, 112));

        label.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        label.setForeground(new java.awt.Color(21, 50, 112));
        label.setText("Address:");

        txtTeam.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtTeam.setForeground(new java.awt.Color(21, 50, 112));
        txtTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtName)
                        .addComponent(jLabel25)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27)
                        .addGroup(panel3Layout.createSequentialGroup()
                            .addComponent(RBF)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RBM))
                        .addComponent(txtLast)
                        .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(label)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(JDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addGap(400, 400, 400))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBF)
                    .addComponent(RBM))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton13)
                .addContainerGap())
        );

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(21, 50, 112));
        jLabel23.setText("Add Student Member");

        pnTitle.setBackground(new java.awt.Color(205, 228, 242));
        pnTitle.setPreferredSize(new java.awt.Dimension(950, 110));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/BackBtn.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(21, 50, 112));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/polytechnic Gym System.png"))); // NOI18N
        jLabel22.setPreferredSize(new java.awt.Dimension(1353, 135));

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addContainerGap())
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTitleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTitleLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton15)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(332, 332, 332))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(pnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBFActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:

        String name;
        String Lname;
        try {
            name = txtName.getText();
            if (name.length() < 2) {
                JOptionPane.showMessageDialog(null, "Please enter a name with at least two letters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return; // Stop further execution if an exception occurs
            }
        } catch (NullPointerException e) {
            // Handle the exception when `txtName` is null
            JOptionPane.showMessageDialog(null, "Please enter a name.", "Missing Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        try {
            Lname = txtLast.getText();
            if (Lname.length() < 2) {
                JOptionPane.showMessageDialog(null, "Please enter a last name with at least two letters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return; // Stop further execution if an exception occurs
            }
        } catch (NullPointerException e) {
            // Handle the exception when `txtLast` is null
            JOptionPane.showMessageDialog(null, "Please enter a last name.", "Missing Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        String gender = "";
        if (RBF.isSelected()) {
            gender = "Female";
        } else if (RBM.isSelected()) {
            gender = "Male";
        } else {
            // Gender not selected
            JOptionPane.showMessageDialog(null, "Please select a gender.", "Missing Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        String course;
        try {
            course = txtCourse.getText();
            if (course.length() == 0) {
                JOptionPane.showMessageDialog(null, "Please enter a course.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return; // Stop further execution if an exception occurs
            }
        } catch (NullPointerException e) {
            // Handle the exception when `txtCourse` is null
            JOptionPane.showMessageDialog(null, "Please enter a course.", "Missing Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        String team;
        try {
            team = txtTeam.getText();
            if (team.length() < 2) {
                JOptionPane.showMessageDialog(null, "Please select a team.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return; // Stop further execution if an exception occurs
            }
        } catch (NullPointerException e) {
            // Handle the exception when `JCteam` is null
            JOptionPane.showMessageDialog(null, "Please select a team.", "Missing Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        String address;
        try {
            address = txtAddress.getText();
            if (address.length() < 4) {
                JOptionPane.showMessageDialog(null, "Please enter an Address with at least four letters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return; // Stop further execution if an exception occurs
            }
        } catch (NullPointerException e) {
            // Handle the exception when `txtName` is null
            JOptionPane.showMessageDialog(null, "Please enter an Address.", "Missing Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        String day = (String) JDay.getSelectedItem();
        String month = (String) Jmonth.getSelectedItem();
        String year = (String) Jyear.getSelectedItem();
        if (day == "Day" || month == "Month" || year == "Year" || day.isEmpty() || month.isEmpty() || year.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a valid date of birth.", "Missing Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }
        String dob = day + month + year;

        int phone;
        try {
            phone = Integer.parseInt(txtphone.getText());
            if (phone < 0) {
                JOptionPane.showMessageDialog(null, "Please enter a valid phone number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return; // Stop further execution if an exception occurs
            }
        } catch (NumberFormatException e) {
            // Handle the exception when the phone number cannot be parsed as an integer
            JOptionPane.showMessageDialog(null, "Please enter a valid phone number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution ifan exception occurs
        } catch (NullPointerException e) {
            // Handle the exception when `txtphone` is null
            JOptionPane.showMessageDialog(null, "Please enter a phone number.", "Missing Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        boolean hasPt = false;

        int id = nextID;
        nextID++;

// Create a new Student object and add it to the memberList
        Student s;
        try {
            Employee personalTrainer = null;
            s = new Student(course, team, name, Lname, dob, phone, gender, hasPt, address, personalTrainer);

        } catch (IllegalArgumentException e) {
            // Handle the exception when the `Student` constructor throws an exception
            JOptionPane.showMessageDialog(null, e.getMessage(), "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        try {
            GymSystem.memberList.add(s);
        } catch (ArrayIndexOutOfBoundsException e) {
            // Handle the exception when the `memberList` is full and cannot add a new `Student` object
            JOptionPane.showMessageDialog(null, "The member list is full and cannot add a new student.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        txtName.setText("");
        txtLast.setText("");
        txtAddress.setText("");
        txtphone.setText("");
        txtCourse.setText("");
        txtTeam.setText("");
        JDay.setSelectedIndex(0);
        Jmonth.setSelectedIndex(0);
        Jyear.setSelectedIndex(0);
        group1.clearSelection();

        JOptionPane.showMessageDialog(null, "Registered successfully", "Done", JOptionPane.PLAIN_MESSAGE);
        System.out.println("Done !");
        for (Member student : GymSystem.memberList) {
            System.out.println(student.toString());
    }//GEN-LAST:event_jButton13ActionPerformed
    }
    private void JyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JyearActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddMem().setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void JmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JmonthActionPerformed

    private void RBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBMActionPerformed

    private void txtTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JDay;
    private javax.swing.JComboBox<String> Jmonth;
    private javax.swing.JComboBox<String> Jyear;
    private javax.swing.JRadioButton RBF;
    private javax.swing.JRadioButton RBM;
    private javax.swing.ButtonGroup group1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private java.awt.Panel panel3;
    private javax.swing.JPanel pnTitle;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTeam;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
