package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import Logic.*;
import static Logic.GymSystem.memberList;
import Logic.Trainer;
import Logic.Employee;
import static Logic.GymSystem.employeeList;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;

public class AssignPt extends javax.swing.JFrame {

    /**
     * Creates new form AssignPt
     */
    public AssignPt() {
        initComponents();
          Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
        refillCombo();
        refillComboMem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        cbTrainers = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbMem = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnTitle = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel7.setBackground(new java.awt.Color(241, 247, 251));
        jPanel7.setPreferredSize(new java.awt.Dimension(950, 600));

        jPanel9.setBackground(new java.awt.Color(205, 228, 242));

        btnLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(21, 50, 112));
        btnLogin.setText("Assign");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        cbTrainers.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cbTrainers.setForeground(new java.awt.Color(21, 50, 112));
        cbTrainers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrainersActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(21, 50, 112));
        jLabel8.setText("Choose Member:");

        cbMem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cbMem.setForeground(new java.awt.Color(21, 50, 112));
        cbMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMemActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(21, 50, 112));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/PT.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(21, 50, 112));
        jLabel11.setText("Choose Trainer:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMem, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(140, 140, 140)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(cbTrainers, 0, 255, Short.MAX_VALUE)
                        .addGap(70, 70, 70))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(332, 332, 332))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTrainers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnLogin)
                .addGap(25, 25, 25))
        );

        pnTitle.setBackground(new java.awt.Color(205, 228, 242));
        pnTitle.setPreferredSize(new java.awt.Dimension(950, 110));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/BackBtn.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(21, 50, 112));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/polytechnic Gym System.png"))); // NOI18N
        jLabel22.setPreferredSize(new java.awt.Dimension(1353, 135));

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addContainerGap())
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTitleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTitleLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton15)))
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(21, 50, 112));
        jLabel9.setText("Assign Personal Trainer");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(389, 389, 389))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(pnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTrainersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrainersActionPerformed
        // TODO add your handling code here:
        cbTrainers.getSelectedItem();
    }//GEN-LAST:event_cbTrainersActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
Trainer selectedTrainer = (Trainer) cbTrainers.getSelectedItem();

// Get the selected member from the combo box
        Member selectedMember = null;
        int selectedIndexMem = cbMem.getSelectedIndex();
        if (selectedIndexMem >= 0) {
            selectedMember = GymSystem.memberList.get(selectedIndexMem);
        }

// Check if the selected member is already assigned to a trainer
        if (selectedMember != null && selectedMember.getPersonalTrainer() != null) {
            Trainer oldTrainer = (Trainer) selectedMember.getPersonalTrainer();

            // Remove the selected member from the old trainer's member list
            oldTrainer.getMemberTList().remove(selectedMember);
        }

// Assign the selected trainer to the selected member
        if (selectedTrainer != null && selectedMember != null) {
            selectedMember.setPersonalTrainer(selectedTrainer);
            selectedTrainer.getMemberTList().add(selectedMember);

            // Print some information about the assignment
            System.out.println("The member " + selectedMember.getFirstName() + " who holds the number " + selectedMember.getMembershipId() + " will be trained by " + selectedTrainer.getFirstName() + ".");
            JOptionPane.showMessageDialog(this, "The member " + selectedMember.getFirstName() + " who holds the number " + selectedMember.getMembershipId() + " will be trained by " + selectedTrainer.getFirstName() + ".");
            System.out.println("List of members for " + selectedTrainer.getFirstName() +":");}

    }

    private boolean isValidID(String id) {
        // Perform the validation logic here
        // Return true if the ID is valid, false otherwise
        return true;
    }

// Assign the personal trainer to the ID (replace this with your own assignment logic)
    private void assignPersonalTrainer(String id, String trainer) {
        // Perform the assignment logic here
        // Use the provided ID and trainer variables to assign the personal trainer to the ID
        // You can store the assignment in your system or update any relevant data structures

    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void cbMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMemActionPerformed
        // TODO add your handling code here:
        cbMem.getSelectedItem();
    }//GEN-LAST:event_cbMemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignPt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignPt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignPt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignPt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignPt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cbMem;
    private javax.swing.JComboBox<Trainer> cbTrainers;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel pnTitle;
    // End of variables declaration//GEN-END:variables

           private void refillCombo() {

        cbTrainers.removeAllItems(); // Remove all items from the combo box

        // Retrieve the list of trainers from the GymSystem class
        ArrayList<Employee> trainerList = GymSystem.employeeList;
        // Loop through the trainerList and add each trainer's name to the combo box
        for (Employee employee : trainerList) {
            if (employee instanceof Trainer) {
                Trainer trainer = (Trainer) employee;
                cbTrainers.addItem(trainer);
            }
        }

    

    }

    private void refillComboMem() {

        cbMem.removeAllItems(); // Remove all items from the combo box

        // Retrieve the list of members from the GymSystem class
        ArrayList<Member> memberList = GymSystem.memberList;
        // Loop through the memberList and add each member's name to the combo box
        for (Member member : memberList) {
            // Assuming the Member class has a method named getName() to retrieve the member's name
            cbMem.addItem(member.getMembershipId() + " " + member.getFirstName());
        }

    }

}
