package GUI;

import Logic.Employee;
import Logic.GymSystem;
import static Logic.GymSystem.employeeList;
import static Logic.GymSystem.memberList;
import Logic.Member;
import Logic.Staff;
import Logic.Student;
import Logic.Trainer;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.*;

public class loginF extends javax.swing.JFrame {

    /**
     * Creates new form loginF
     */
    public loginF() {
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
        
        GymSystem gymm = new GymSystem();
        Member member = new Member();
        Employee emp = new Employee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(950, 600));

        jPanel1.setBackground(new java.awt.Color(241, 247, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 600));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(205, 228, 242));
        jPanel2.setPreferredSize(new java.awt.Dimension(950, 110));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 50, 112));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/polytechnic Gym System.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(1353, 135));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 950, 102);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 50, 112), 3, true));

        btnLogin.setBackground(new java.awt.Color(247, 251, 253));
        btnLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(21, 50, 112));
        btnLogin.setText("Login");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 50, 112), 3, true));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 50, 112));
        jLabel1.setText("To start the program press this button:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/gym.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/gym.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(69, 69, 69))))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(110, 170, 690, 360);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1050, 108, 0, 0);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/1234567.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-10, 100, 1260, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        System.out.println("In Login button");
        // TODO add your handling code here:
        //next frame
        setVisible(false);
        new Menu().setVisible(true);
        File dataFile = new File("data.dat");
        if (dataFile.exists()) {
            System.out.println("Serialized File exists");
            

            try {
                FileInputStream Myfile = new FileInputStream("data.dat");
                ObjectInputStream in = new ObjectInputStream(Myfile);

              GymSystem.setEmployeeList((ArrayList<Employee>) in.readObject());
              GymSystem.setMemberList((ArrayList<Member>) in.readObject());
              Employee.setStaffId((int) in.readObject());
              Member.setNextId((int) in.readObject());
             
               

                System.out.println("Data deserialized from data.dat");
            } catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException | ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        } else if (!dataFile.exists()) {
            try {
                createUsers();

            } catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(loginF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
  public void createUsers() throws FileNotFoundException {

        File startUpFile = new File("startup.txt");

        employeeList.clear();
        memberList.clear();
        FileReader file = new FileReader(startUpFile);
        Scanner scan = new Scanner(file);
        String emNum = scan.nextLine();
        int emNumInt = Integer.parseInt(emNum);
        for (int i = 0; i < emNumInt; i++) {
            String employeeType = scan.nextLine().trim();

            if (employeeType.equalsIgnoreCase("PT")) {
                creatept(scan);

            } else if (employeeType.equalsIgnoreCase("E")) {
                createREmp(scan);

            }

        }

    }

    public static void creatept(Scanner scan) {
        System.out.println("In createept");
        String firstName = scan.nextLine();
        String lastName = scan.nextLine();
        String address = scan.nextLine();
        Integer phone = Integer.parseInt(scan.nextLine());
        double salary = Double.parseDouble(scan.nextLine());
        String gender = "";
        String dob = "";
        boolean isPt = true;
        // 
        Trainer pt = new Trainer(firstName, lastName, address, dob, phone, gender, salary, isPt);
        employeeList.add(pt);
        Member m = null;

        int numMem = Integer.parseInt(scan.nextLine());
        for (int i = 0; i < numMem; i++) {
            String memType = scan.nextLine();
            if (memType.equalsIgnoreCase("Staff")) {
                creatStaff(scan, pt);

            } else if (memType.equalsIgnoreCase("Student")) {
                creatStudent(scan, pt);

            }
        }
    }

    public static void creatStudent(Scanner scan, Trainer pt) {
        String firstName = scan.nextLine();
        String lastName = scan.nextLine();
        String address = scan.nextLine();
        String dob = scan.nextLine();
        Integer phone = Integer.parseInt(scan.nextLine());
        String gender = scan.nextLine();
        String course = scan.nextLine();
        String team = scan.nextLine();

        boolean hasPt = true;

        Student s = new Student(course, team, firstName, lastName, dob, phone, gender, hasPt, address, pt);
        memberList.add(s);
        // pt.assignMember(s);
        pt.getMemberTList().add(s);
    }

    public static void creatStaff(Scanner scan, Trainer pt) {
        String firstName = scan.nextLine();
        String lastName = scan.nextLine();
        String address = scan.nextLine();
        String dob = scan.nextLine();
        Integer phone = Integer.parseInt(scan.nextLine());
        String gender = scan.nextLine();
        String position = scan.nextLine();
        String department = scan.nextLine();

        boolean hasPt = true;

        Staff s = new Staff(position, department, firstName, lastName, dob, phone, gender, hasPt, address, pt);
        memberList.add(s);
        // pt.assignMember(s);
        pt.getMemberTList().add(s);
    }

    public static void createREmp(Scanner scan) {
        String firstName = scan.nextLine();
        String lastName = scan.nextLine();
        String address = scan.nextLine();
        Integer phone = Integer.parseInt(scan.nextLine());
        double salary = Double.parseDouble(scan.nextLine());
        boolean isPt = false;
        String dob = "";
        String gender = "";
        Employee emp = new Employee(firstName, lastName, address, dob, phone, gender, salary, false);
        employeeList.add(emp);
    }

}
