package GUI;

import Logic.Employee;
import Logic.GymSystem;
import Logic.Member;
import Logic.Staff;
import Logic.Student;
import Logic.Trainer;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMenu = new javax.swing.JPanel();
        pnTitle = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        btnAddMembers = new javax.swing.JButton();
        btnAssignPT = new javax.swing.JButton();
        btnAddEmployees = new javax.swing.JButton();
        btnModifyMembers = new javax.swing.JButton();
        btnModifyEmployees = new javax.swing.JButton();
        btnMarkRep = new javax.swing.JButton();
        btnListPT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panMenu.setBackground(new java.awt.Color(241, 247, 251));
        panMenu.setPreferredSize(new java.awt.Dimension(950, 600));

        pnTitle.setBackground(new java.awt.Color(205, 228, 242));
        pnTitle.setPreferredSize(new java.awt.Dimension(950, 110));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/CloseBtn.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(21, 50, 112));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/polytechnic Gym System.png"))); // NOI18N
        jLabel22.setPreferredSize(new java.awt.Dimension(1353, 135));

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(20, 20, 20))
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTitleLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton2))
                    .addGroup(pnTitleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        btnAddMembers.setBackground(new java.awt.Color(205, 228, 242));
        btnAddMembers.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnAddMembers.setForeground(new java.awt.Color(21, 50, 112));
        btnAddMembers.setText("Add Members");
        btnAddMembers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 50, 112), 3, true));
        btnAddMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMembersActionPerformed(evt);
            }
        });

        btnAssignPT.setBackground(new java.awt.Color(205, 228, 242));
        btnAssignPT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnAssignPT.setForeground(new java.awt.Color(21, 50, 112));
        btnAssignPT.setText("Assign to personal Trainer");
        btnAssignPT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 50, 112), 3, true));
        btnAssignPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignPTActionPerformed(evt);
            }
        });

        btnAddEmployees.setBackground(new java.awt.Color(205, 228, 242));
        btnAddEmployees.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnAddEmployees.setForeground(new java.awt.Color(21, 50, 112));
        btnAddEmployees.setText("Add Employees");
        btnAddEmployees.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 50, 112), 3, true));
        btnAddEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeesActionPerformed(evt);
            }
        });

        btnModifyMembers.setBackground(new java.awt.Color(205, 228, 242));
        btnModifyMembers.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnModifyMembers.setForeground(new java.awt.Color(21, 50, 112));
        btnModifyMembers.setText("Modify / Delete Member");
        btnModifyMembers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 50, 112), 3, true));
        btnModifyMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyMembersActionPerformed(evt);
            }
        });

        btnModifyEmployees.setBackground(new java.awt.Color(205, 228, 242));
        btnModifyEmployees.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnModifyEmployees.setForeground(new java.awt.Color(21, 50, 112));
        btnModifyEmployees.setText("Modify / Delete Employee");
        btnModifyEmployees.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 50, 112), 3, true));
        btnModifyEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifyEmployeesMouseClicked(evt);
            }
        });
        btnModifyEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyEmployeesActionPerformed(evt);
            }
        });

        btnMarkRep.setBackground(new java.awt.Color(205, 228, 242));
        btnMarkRep.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnMarkRep.setForeground(new java.awt.Color(21, 50, 112));
        btnMarkRep.setText("Marketing Report");
        btnMarkRep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 50, 112), 3, true));
        btnMarkRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkRepActionPerformed(evt);
            }
        });

        btnListPT.setBackground(new java.awt.Color(205, 228, 242));
        btnListPT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnListPT.setForeground(new java.awt.Color(21, 50, 112));
        btnListPT.setText("List of Personal Trainers");
        btnListPT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 50, 112), 3, true));
        btnListPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPTActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons1.png"))); // NOI18N

        javax.swing.GroupLayout panMenuLayout = new javax.swing.GroupLayout(panMenu);
        panMenu.setLayout(panMenuLayout);
        panMenuLayout.setHorizontalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panMenuLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(btnAddMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(113, 113, 113)
                .addGroup(panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMarkRep, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(btnModifyMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifyEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAssignPT, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        panMenuLayout.setVerticalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addComponent(pnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModifyMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnListPT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignPT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnMarkRep, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignPTActionPerformed
        setVisible(false);
        new AssignPt().setVisible(true);

    }//GEN-LAST:event_btnAssignPTActionPerformed

    private void btnAddMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMembersActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddMem().setVisible(true);

    }//GEN-LAST:event_btnAddMembersActionPerformed

    private void btnAddEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeesActionPerformed
        setVisible(false);
        new AddEmp().setVisible(true);

    }//GEN-LAST:event_btnAddEmployeesActionPerformed

    private void btnModifyMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyMembersActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ModifyMem().setVisible(true);

    }//GEN-LAST:event_btnModifyMembersActionPerformed

    private void btnModifyEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyEmployeesActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ModEmp().setVisible(true);

    }//GEN-LAST:event_btnModifyEmployeesActionPerformed

    private void btnMarkRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkRepActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new MarkR().setVisible(true);

    }//GEN-LAST:event_btnMarkRepActionPerformed

    private void btnListPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPTActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ListPT().setVisible(true);

    }//GEN-LAST:event_btnListPTActionPerformed

    private void btnModifyEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifyEmployeesMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new ModEmp().setVisible(true);
    }//GEN-LAST:event_btnModifyEmployeesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FileOutputStream Myfile;
        try {
            Myfile = new FileOutputStream("data.dat");
            ObjectOutputStream out = new ObjectOutputStream(Myfile);

            // Serialize employeeList and memberList
            out.writeObject(Logic.GymSystem.employeeList);  // Serialize the list of employees
            out.writeObject(Logic.GymSystem.memberList);
            // Serialize the list of members
            out.writeObject(Logic.Employee.getStaffId());
            out.writeObject(Logic.Member.getNextId());

            // Serialize memberTList for each Trainer
            for (Employee employee : Logic.GymSystem.employeeList) {
                if (employee instanceof Trainer) {        // Check if the employee is a Trainer
                    Trainer trainer = (Trainer) employee;
                    out.writeObject(trainer.getMemberTList());  // Serialize the memberTList for the Trainer
                }
            }

            System.out.println("Data saved to data.dat");
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to exit Application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GymSystem gymSystem = new GymSystem();

                // Deserialize data
                gymSystem.deserializeData("data.dat");

                // Perform operations and interact with the gym system
                // Serialize data
                gymSystem.serializeData("data.dat");
                new Menu().setVisible(true);

            }
        });
    }

//    private void initializeSystem() {
//        // Check if the system has already been initialized
//        File dataFile = new File("startup.txt");
//        if (dataFile.exists()) {
//            JOptionPane.showMessageDialog(this, "System already initialized.");
//            return;
//        }
//
//        // Read the startup.txt file
//        try {
//            BufferedReader reader = new BufferedReader(new FileReader("startup.txt"));
//            int numEmployees = Integer.parseInt(reader.readLine().trim());
//            ArrayList<Employee> employees = new ArrayList<>();
//            for (int i = 0; i < numEmployees; i++) {
//                String employeeType = reader.readLine().trim();
//                if (employeeType.equals("E")) {
//                    Employee employee = new Employee();
//                    employee.setFirstName(reader.readLine().trim());
//                    employee.setSurname(reader.readLine().trim());
//                    employee.setAddress(reader.readLine().trim());
//                    employee.setPhone(Integer.parseInt(reader.readLine().trim()));
//                    employee.setSalary(Double.parseDouble(reader.readLine().trim()));
//                    employees.add(employee);
//                } else if (employeeType.equals("PT")) {
//                    Trainer trainer = new Trainer();
//                    trainer.setFirstName(reader.readLine().trim());
//                    trainer.setSurname(reader.readLine().trim());
//                    trainer.setAddress(reader.readLine().trim());
//                    trainer.setPhone(Integer.parseInt(reader.readLine().trim()));
//                    trainer.setSalary(Double.parseDouble(reader.readLine().trim()));
//                    int numMembers = Integer.parseInt(reader.readLine().trim());
//                    ArrayList<Member> members = new ArrayList<>();
//                    for (int j = 0; j < numMembers; j++) {
//                        String memberType = reader.readLine().trim();
//                        Member member;
//                        if (memberType.equals("staff")) {
//                            member = new Staff();
//                            ((Staff) member).setPosition(reader.readLine().trim());
//                            ((Staff) member).setDepartment(reader.readLine().trim());
//                        } else {
//                            member = new Student();
//                            ((Student) member).setCourse(reader.readLine().trim());
//                            ((Student) member).setTeam(reader.readLine().trim());
//                        }
//
//                        member.setFirstName(reader.readLine().trim());
//                        member.setSurname(reader.readLine().trim());
//                        member.setAddress(reader.readLine().trim());
//                        member.setDateOfBirth(reader.readLine().trim());
//                        member.setPhone(Integer.parseInt(reader.readLine().trim()));
//                        member.setGender(reader.readLine().trim());
//                        members.add(member);
//                    }
//                    trainer.setMemberTList(members);
//                    employees.add(trainer);
//                }
//            }
//            reader.close();
//
//            // Initialize the system with the data from startup.txt
//            // (code to initialize system with data goes here)
//            // Serialize the data so it can be used in future runs
//            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("data.dat"));
//            oos.writeObject(employees.toArray(new Employee[employees.size()]));
//            oos.close();
//
//            JOptionPane.showMessageDialog(this, "System initialized successfully!");
//        } catch (IOException ex) {
//            ex.printStackTrace();
//        }
//    }
//   public static void serializeData(String filename, List<Employee> employees, List<Member> members) {
//        try {
//            FileOutputStream fileOut = new FileOutputStream(filename);
//            ObjectOutputStream out = new ObjectOutputStream(fileOut);
//
//            // Serialize employeeList and memberList
//            out.writeObject(employees);
//            out.writeObject(members);
//
//            // Serialize memberTList for each Trainer
//            for (Employee employee : employees) {
//                if (employee instanceof Trainer) {
//                    Trainer trainer = (Trainer) employee;
//                    out.writeObject(trainer.getMemberTList());
//                }
//            }
//
//            out.close();
//            fileOut.close();
//            System.out.println("Data serialized and saved to " + filename);
//        } catch (IOException ex) {
//            System.out.println("Serialization error: " + ex.getMessage());
//}}
//
//    public static void deserializeData(String filename) {
//        List<Employee> employees = new ArrayList<>();
//        List<Member> members = new ArrayList<>();
//
//        try {
//            FileInputStream fileIn = new FileInputStream(filename);
//            ObjectInputStream in = new ObjectInputStream(fileIn);
//
//            // Deserialize employeeList and memberList
//            employees = (List<Employee>) in.readObject();
//            members = (List<Member>) in.readObject();
//
//            // Deserialize memberTList for each Trainer
//            for (Employee employee : employees) {
//                if (employee instanceof Trainer) {
//                    Trainer trainer = (Trainer) employee;
//                    List<Member> memberTList = (List<Member>) in.readObject();
//                    trainer.setMemberTList((ArrayList<Member>) memberTList);
//                }
//            }
//
//            in.close();
//            fileIn.close();
//            System.out.println("Data deserialized from " + filename);
//        } catch (FileNotFoundException ex) {
//            System.out.println("File not found: " + filename);
//        } catch (IOException | ClassNotFoundException ex) {
//            System.out.println("Error while deserializing data: " + ex.getMessage());
//        }
//
//        String displayText = generateDisplayText(employees, members);
//
//        // Update the GUI or perform further operations with the display text
//      txtInfo.setText(displayText);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployees;
    private javax.swing.JButton btnAddMembers;
    private javax.swing.JButton btnAssignPT;
    private javax.swing.JButton btnListPT;
    private javax.swing.JButton btnMarkRep;
    private javax.swing.JButton btnModifyEmployees;
    private javax.swing.JButton btnModifyMembers;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel panMenu;
    private javax.swing.JPanel pnTitle;
    // End of variables declaration//GEN-END:variables
}
