package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import Logic.*;
import static Logic.GymSystem.employeeList;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

import javax.swing.JOptionPane;

public class ModEmp extends javax.swing.JFrame {

    /**
     * Creates new form ModEmp
     */
    public ModEmp() {
        initComponents();
        refillCombo();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        f = new javax.swing.JRadioButton();
        m = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDay = new javax.swing.JComboBox<>();
        Jmonth = new javax.swing.JComboBox<>();
        Jyear = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        Delete = new javax.swing.JButton();
        Modify = new javax.swing.JButton();
        view = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnTitle1 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        cbEmployee = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(241, 247, 251));
        jPanel1.setForeground(new java.awt.Color(21, 50, 112));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 600));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(21, 50, 112));
        jLabel4.setText("Modify/Delete Employee");

        panel1.setBackground(new java.awt.Color(205, 228, 242));
        panel1.setPreferredSize(new java.awt.Dimension(850, 350));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 50, 112));
        jLabel1.setText("First Name:");

        txtname.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtname.setForeground(new java.awt.Color(21, 50, 112));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 50, 112));
        jLabel3.setText("Surname:");

        txtlname.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtlname.setForeground(new java.awt.Color(21, 50, 112));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(21, 50, 112));
        jLabel5.setText("Gender:");

        buttonGroup1.add(f);
        f.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        f.setForeground(new java.awt.Color(21, 50, 112));
        f.setText("Female");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        buttonGroup1.add(m);
        m.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        m.setForeground(new java.awt.Color(21, 50, 112));
        m.setText("Male");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(21, 50, 112));
        jLabel6.setText("Salary:");

        txtsalary.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtsalary.setForeground(new java.awt.Color(21, 50, 112));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(21, 50, 112));
        jLabel7.setText("Address:");

        txtAddress.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(21, 50, 112));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(21, 50, 112));
        jLabel8.setText("Date of Birth:");

        jDay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jDay.setForeground(new java.awt.Color(21, 50, 112));
        jDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDayActionPerformed(evt);
            }
        });

        Jmonth.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        Jmonth.setForeground(new java.awt.Color(21, 50, 112));
        Jmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May ", "June", "July", "August", "September", "October", "November", "December" }));
        Jmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmonthActionPerformed(evt);
            }
        });

        Jyear.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        Jyear.setForeground(new java.awt.Color(21, 50, 112));
        Jyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008" }));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(21, 50, 112));
        jLabel9.setText("Phone number:");

        txtPhone.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(21, 50, 112));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(21, 50, 112));
        jLabel10.setText("Are you a Personal Trainer:");

        buttonGroup2.add(yes);
        yes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        yes.setForeground(new java.awt.Color(21, 50, 112));
        yes.setText("Yes");

        buttonGroup2.add(no);
        no.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        no.setForeground(new java.awt.Color(21, 50, 112));
        no.setText("No");

        Delete.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        Delete.setForeground(new java.awt.Color(21, 50, 112));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Modify.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        Modify.setForeground(new java.awt.Color(21, 50, 112));
        Modify.setText("Modify");
        Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(f)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(m))
                    .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtlname, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtsalary, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(Delete)
                        .addGap(45, 45, 45)
                        .addComponent(Modify)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(yes)
                                .addGap(18, 18, 18)
                                .addComponent(no))
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yes)
                    .addComponent(no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete)
                    .addComponent(Modify))
                .addContainerGap())
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f)
                    .addComponent(m))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        view.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        view.setForeground(new java.awt.Color(21, 50, 112));
        view.setText("View Details");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(21, 50, 112));
        jLabel12.setText("Employee ID:");

        pnTitle1.setBackground(new java.awt.Color(205, 228, 242));
        pnTitle1.setPreferredSize(new java.awt.Dimension(950, 110));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/BackBtn.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(21, 50, 112));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/polytechnic Gym System.png"))); // NOI18N
        jLabel22.setPreferredSize(new java.awt.Dimension(1353, 135));

        javax.swing.GroupLayout pnTitle1Layout = new javax.swing.GroupLayout(pnTitle1);
        pnTitle1.setLayout(pnTitle1Layout);
        pnTitle1Layout.setHorizontalGroup(
            pnTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitle1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addContainerGap())
        );
        pnTitle1Layout.setVerticalGroup(
            pnTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitle1Layout.createSequentialGroup()
                .addGroup(pnTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTitle1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTitle1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton15)))
                .addContainerGap())
        );

        cbEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(cbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(view))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(330, 330, 330)
                                .addComponent(jLabel4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view)
                    .addComponent(cbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here
        // TODO add your handling code here
        Employee emp = GymSystem.employeeList.get(cbEmployee.getSelectedIndex());
        String gender = emp.getGender();
        // Set the text fields with existing member information
        txtname.setText(emp.getFirstName());
        txtlname.setText(emp.getSurname());
        txtAddress.setText(emp.getAddress());
        txtPhone.setText(Integer.toString(emp.getPhone()));
        txtsalary.setText(Double.toString(emp.getSalary()));;

    }//GEN-LAST:event_viewActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:

        // Get the selected Employee from the employeeList
        Employee selectedEmployee = (Employee) cbEmployee.getSelectedItem();

        if (selectedEmployee != null) {

            if (selectedEmployee instanceof Trainer) {
                Trainer selectedTrainer = (Trainer) selectedEmployee;
                // Get the first member from the selected trainer's memberTList
                selectedTrainer.getMemberTList().clear();               // Remove the selected member from the gym system's memberList

                // Remove the selected member from the selected trainer's memberTList
                // Remove the selected trainer from the gym system's employeeList
                GymSystem.employeeList.remove(selectedTrainer);
                JOptionPane.showMessageDialog(this, "Trainer has been deleted");
            } else {
                GymSystem.employeeList.remove(selectedEmployee);
                JOptionPane.showMessageDialog(this, "Employee has been deleted");

            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyActionPerformed
        // TODO add your handling code here:
        //do the search 
        Employee emp = GymSystem.employeeList.get(cbEmployee.getSelectedIndex());

        // Validate and retrieve modified information
        String modifiedFirstName = txtname.getText();
        String modifiedSurname = txtlname.getText();

        String gender;
        if (f.isSelected()) {
            gender = "Female";
        } else if (m.isSelected()) {
            gender = "Male";
        } else {
            // Gender not selected
            JOptionPane.showMessageDialog(null, "Please select a gender.", "Missing Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }
        String modifiedGender = gender;

        Double modifiedSalary = Double.valueOf(txtsalary.getText());

        if (modifiedSalary < 0) {
            throw new IllegalArgumentException("Salary cannot be negative.");

        }

        if (modifiedSalary < 0) {
            JOptionPane.showMessageDialog(null, "Please enter a correct salary.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        String modifiedAddress;
        try {
            modifiedAddress = txtAddress.getText();
            if (modifiedAddress.length() < 4) {
                JOptionPane.showMessageDialog(null, "Please enter an address with at least four letters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return; // Stop further execution if an exception occurs
            }
        } catch (NullPointerException e) {
            // Handle the exception when `txtAddress` is null
            JOptionPane.showMessageDialog(null, "Please enter an address.", "Missing Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        String modifiedDay = (String) jDay.getSelectedItem();
        String modifiedMonth = (String) Jmonth.getSelectedItem();
        String modifiedYear = (String) Jyear.getSelectedItem();
        if (modifiedDay.equals("Day") || modifiedMonth.equals("Month") || modifiedYear.equals("Year") || modifiedDay.isEmpty() || modifiedMonth.isEmpty() || modifiedYear.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a valid date of birth.", "Missing Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }
        String modifiedDateOfBirth = modifiedDay + modifiedMonth + modifiedYear;

        int modifiedPhone;
        try {
            modifiedPhone = Integer.parseInt(txtPhone.getText());
        } catch (NumberFormatException e) {
            // Handle the exception when the phone number cannot be parsed as an integer
            JOptionPane.showMessageDialog(null, "Please enter a valid phone number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        boolean modifiedIsPt = false;
        if (yes.isSelected()) {
            modifiedIsPt = true;
        } else if (no.isSelected()) {
            modifiedIsPt = false;
        } else {
            // Personal trainer selection not made
            JOptionPane.showMessageDialog(null, "Please select whether the member has a personal trainer or not.", "Missing Input", JOptionPane.ERROR_MESSAGE);
            // Stop further execution if an exception occurs
        }

        // Validate modified first name and surname
        if (modifiedFirstName.length() < 2) {
            JOptionPane.showMessageDialog(null, "Please enter a first name with at least two letters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        if (modifiedSurname.length() < 2) {
            JOptionPane.showMessageDialog(null, "Please enter a surname with at least two letters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if an exception occurs
        }

        // Update member information
        emp.setFirstName(modifiedFirstName);
        emp.setSurname(modifiedSurname);
        emp.setGender(modifiedGender);
        emp.setSalary(modifiedSalary);
        emp.setDateOfBirth(modifiedDateOfBirth);
        emp.setPhone(modifiedPhone);
        emp.setIsPersonalTrainer(modifiedIsPt);
        emp.setAddress(modifiedAddress);

        // Display success message
        JOptionPane.showMessageDialog(null, "Employee modified successfully.", "Modification Complete", JOptionPane.PLAIN_MESSAGE);
        System.out.println("modified");
        System.out.println(employeeList);


    }//GEN-LAST:event_ModifyActionPerformed

    private void jDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDayActionPerformed

    private void JmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JmonthActionPerformed

    private void cbEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEmployeeActionPerformed
        // TODO add your handling code here:
        cbEmployee.getSelectedItem();
    }//GEN-LAST:event_cbEmployeeActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JComboBox<String> Jmonth;
    private javax.swing.JComboBox<String> Jyear;
    private javax.swing.JButton Modify;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<Employee> cbEmployee;
    private javax.swing.JRadioButton f;
    private javax.swing.JButton jButton15;
    private javax.swing.JComboBox<String> jDay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton m;
    private javax.swing.JRadioButton no;
    private java.awt.Panel panel1;
    private javax.swing.JPanel pnTitle1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JButton view;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables
private void refillCombo() {

        cbEmployee.removeAllItems(); // Remove all items from the combo box

        // Retrieve the list of trainers from the GymSystem class
        ArrayList<Employee> trainerList = GymSystem.employeeList;
        // Loop through the trainerList and add each trainer's name to the combo box
        for (Employee employee : employeeList) {
            // Check if the employee is an instance of the Trainer class
            // Assuming the Trainer class has a method named getName() to retrieve the trainer's name
            cbEmployee.addItem(employee);
        }
    }
}
