package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import Logic.*;
import static Logic.GymSystem.memberList;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

public class ModPolyStaff extends javax.swing.JFrame {

    /**
     * Creates new form ModM
     */
    public ModPolyStaff() {
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        f = new javax.swing.JRadioButton();
        m = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        textposition = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDay = new javax.swing.JComboBox<>();
        Jmonth = new javax.swing.JComboBox<>();
        Jyear = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        Modify = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnTitle1 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(241, 247, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 600));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(21, 50, 112));
        jLabel4.setText("Modify/Delete Poly Staff Member");

        panel1.setBackground(new java.awt.Color(205, 228, 242));
        panel1.setName(""); // NOI18N
        panel1.setPreferredSize(new java.awt.Dimension(850, 350));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 50, 112));
        jLabel1.setText("First Name:");

        txtname.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtname.setForeground(new java.awt.Color(21, 50, 112));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 50, 112));
        jLabel3.setText("Surname:");

        txtlname.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtlname.setForeground(new java.awt.Color(21, 50, 112));
        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(21, 50, 112));
        jLabel5.setText("Gender:");

        buttonGroup1.add(f);
        f.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        f.setForeground(new java.awt.Color(21, 50, 112));
        f.setText("Female");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        buttonGroup1.add(m);
        m.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        m.setForeground(new java.awt.Color(21, 50, 112));
        m.setText("Male");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(21, 50, 112));
        jLabel6.setText("Position:");

        textposition.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        textposition.setForeground(new java.awt.Color(21, 50, 112));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(21, 50, 112));
        jLabel7.setText("Address:");

        txtAddress.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(21, 50, 112));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(21, 50, 112));
        jLabel8.setText("Date of Birth:");

        jDay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jDay.setForeground(new java.awt.Color(21, 50, 112));
        jDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Jmonth.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        Jmonth.setForeground(new java.awt.Color(21, 50, 112));
        Jmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May ", "June", "July", "August", "September", "October", "November", "December" }));

        Jyear.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        Jyear.setForeground(new java.awt.Color(21, 50, 112));
        Jyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008" }));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(21, 50, 112));
        jLabel9.setText("Phone number:");

        txtPhone.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(21, 50, 112));

        Delete.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        Delete.setForeground(new java.awt.Color(21, 50, 112));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Modify.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        Modify.setForeground(new java.awt.Color(21, 50, 112));
        Modify.setText("Modify");
        Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(21, 50, 112));
        jLabel13.setText("Department:");

        txtDepartment.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDepartment.setForeground(new java.awt.Color(21, 50, 112));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete)
                .addGap(28, 28, 28)
                .addComponent(Modify)
                .addGap(324, 324, 324))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(f)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(m))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(textposition, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(60, 60, 60))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f)
                            .addComponent(m)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete)
                    .addComponent(Modify))
                .addContainerGap())
        );

        txtId.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtId.setForeground(new java.awt.Color(21, 50, 112));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        search.setForeground(new java.awt.Color(21, 50, 112));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(21, 50, 112));
        jLabel12.setText("Member ID:");

        pnTitle1.setBackground(new java.awt.Color(205, 228, 242));
        pnTitle1.setPreferredSize(new java.awt.Dimension(950, 110));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/BackBtn.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(21, 50, 112));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/polytechnic Gym System.png"))); // NOI18N
        jLabel22.setPreferredSize(new java.awt.Dimension(1353, 135));

        javax.swing.GroupLayout pnTitle1Layout = new javax.swing.GroupLayout(pnTitle1);
        pnTitle1.setLayout(pnTitle1Layout);
        pnTitle1Layout.setHorizontalGroup(
            pnTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitle1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addContainerGap())
        );
        pnTitle1Layout.setVerticalGroup(
            pnTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitle1Layout.createSequentialGroup()
                .addGroup(pnTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTitle1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTitle1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton15)))
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(229, 229, 229)
                                .addComponent(jLabel4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addGap(28, 28, 28)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtId.getText());
            boolean found = false;
            for (Member member : GymSystem.memberList) {
                if (member.getMembershipId() == id) {
                    if (member instanceof Staff) {
                        // Do something with the found student
// Handle gender selection
                        // Set the text fields with existing member information
                        txtname.setText(member.getFirstName());
                        txtlname.setText(member.getSurname());
                        txtAddress.setText(member.getAddress());
                        txtPhone.setText(Integer.toString(member.getPhone()));
                        textposition.setText(((Staff) member).getPosition());
                        txtDepartment.setText(((Staff) member).getDepartment());

                    } else {
                        JOptionPane.showMessageDialog(null, "Member found, but not a staff");
                    }
                    found = true;
                    break;
                }
            }
            if (!found) {
                JOptionPane.showMessageDialog(null, "Member not found");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "An error occurred: " + ex.getMessage());
        }
    }//GEN-LAST:event_searchActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ModifyMem().setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtId.getText());
            boolean found = false;
            Member memberToRemove = null;
            for (Member member : memberList) {
                if (member.getMembershipId() == id) {
                    if (member instanceof Staff) {
                        // Remove the member from the member list
                        memberToRemove = member;
                        found = true;
                        break;
                    } else {
                        JOptionPane.showMessageDialog(null, "Member found, but not a Staff");
                        return;
                    }
                }
            }
            if (!found) {
                JOptionPane.showMessageDialog(null, "Member not found");
                return;
            }

            // Remove the member from any trainer's trainee list in the employeeList
            for (Employee employee : GymSystem.employeeList) {
                if (employee instanceof Trainer) {
                    Trainer trainer = (Trainer) employee;
                    if (trainer.hasTrainee(memberToRemove)) {
                        trainer.removeMember(memberToRemove);
                    }
                }
            }

            memberList.remove(memberToRemove);
            JOptionPane.showMessageDialog(null, "Member deleted");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "An error occurred: " + ex.getMessage());
        }
        System.out.println("Done !");
        for (Member student : memberList) {
            System.out.println(student.toString());
        }
        JOptionPane.showMessageDialog(null, "Member Deleted successfully.", "Modification Complete", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_DeleteActionPerformed

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtId.getText());
            boolean found = false;
            for (Member member : GymSystem.memberList) {
                if (member.getMembershipId() == id) {
                    if (member instanceof Staff) {
                        Staff staff = (Staff) member; // Cast Member to Student

                        String name = txtname.getText();
                        String Lname = txtlname.getText();
                        // Validate first name and surname
                        if (name.length() < 2) {
                            JOptionPane.showMessageDialog(null, "Please enter a first name with at least two letters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                            return; // Stop further execution if an exception occurs
                        }

                        if (Lname.length() < 2) {
                            JOptionPane.showMessageDialog(null, "Please enter a surname with at least two letters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                            return; // Stop further execution if an exception occurs
                        }
                        staff.setFirstName(name);
                        staff.setSurname(Lname);

                        String gender = "";
                        if (f.isSelected()) {
                            gender = "Female";
                        } else if (m.isSelected()) {
                            gender = "Male";
                        }
                        staff.setGender(gender);

                        String position = textposition.getText();
                        if (position.isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Please enter a position.", "Missing Input", JOptionPane.ERROR_MESSAGE);
                            return; // Stop further execution if an exception occurs
                        }

                        if (position.length() < 3) {
                            JOptionPane.showMessageDialog(null, "Please enter a more than 3 letters.", "Missing Input", JOptionPane.ERROR_MESSAGE);
                            return; // Stop further execution if an exception occurs
                        }

                        staff.setPosition(position);

                        String department = txtDepartment.getText();
                        if (department.length() < 0 || department.isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Please select a department.", "Missing Input", JOptionPane.ERROR_MESSAGE);
                            return; // Stop further execution if an exception occurs
                        }
                        staff.setDepartment(department);

                        String address;
                        try {
                            address = txtAddress.getText();
                            if (address.length() < 4) {
                                JOptionPane.showMessageDialog(null, "Please enter an Address with at least four letters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                                return; // Stop further execution if an exception occurs
                            }
                        } catch (NullPointerException e) {
                            // Handle the exception when `txtName` is null
                            JOptionPane.showMessageDialog(null, "Please enter an Address.", "Missing Input", JOptionPane.ERROR_MESSAGE);
                            return; // Stop further execution if an exception occurs
                        }
                        staff.setAddress(address);

                        String day = (String) jDay.getSelectedItem();
                        String month = (String) Jmonth.getSelectedItem();
                        String year = (String) Jyear.getSelectedItem();
                        if (day == "Day" || month == "Month" || year == "Year" || day.isEmpty() || month.isEmpty() || year.isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Please select a valid date of birth.", "Missing Input", JOptionPane.ERROR_MESSAGE);
                            return; // Stop further execution if an exception occurs
                        }
                        String dateOfBirth = day + month + year;
                        staff.setDateOfBirth(dateOfBirth);
                        int phone;
                        try {
                            phone = Integer.parseInt(txtPhone.getText());
                        } catch (NumberFormatException e) {
                            // Handle the exception when the phone number cannot be parsed as an integer
                            JOptionPane.showMessageDialog(null, "Please enter a valid phone number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                            return; // Stop further execution if an exception occurs
                        }
                        staff.setPhone(phone);

                        boolean hasPt = false;

                        staff.setHasPT(hasPt);
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "An error occurred: " + ex.getMessage());
        }
        JOptionPane.showMessageDialog(null, "Member modified successfully.", "Modification Complete", JOptionPane.PLAIN_MESSAGE);

        System.out.println(memberList);


    }//GEN-LAST:event_ModifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModPolyStaff.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModPolyStaff.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModPolyStaff.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModPolyStaff.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModPolyStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JComboBox<String> Jmonth;
    private javax.swing.JComboBox<String> Jyear;
    private javax.swing.JButton Modify;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton f;
    private javax.swing.JButton jButton15;
    private javax.swing.JComboBox<String> jDay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton m;
    private java.awt.Panel panel1;
    private javax.swing.JPanel pnTitle1;
    private javax.swing.JButton search;
    private javax.swing.JTextField textposition;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
